/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package punto_de_venta.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;

/**
 *
 * @author Nelson
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     * @param dolar
     * @param bs
     */
    public void changeTasa(double dolar, double bs){
        String bs_string = Double.toString(bs);
        String dolar_string = Double.toString(dolar);
        
        money_dolar.setText(dolar_string);
        money_bs.setText(bs_string);
    }

    
    public home() {
        initComponents();
        
        monto_personalidado.setVisible(false);        
        monto_personalidado_label.setVisible(false);
        
        ActionListener ButtonRadioListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                var button = (AbstractButton) e.getSource();
                var valor = button.getText();
                System.out.println("Select: " + valor);
                if("Personalizado".equals(valor)){
                    monto_personalidado.setVisible(true);        
                    monto_personalidado_label.setVisible(true);
                }else{
                    monto_personalidado.setVisible(false);        
                    monto_personalidado_label.setVisible(false);
                }
            }
        };
        bcv_radio.addActionListener(ButtonRadioListener);
        dolar_paralelo_radio.addActionListener(ButtonRadioListener);
        monitor_dolar_radio.addActionListener(ButtonRadioListener);
        personalizado_radio.addActionListener(ButtonRadioListener);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        javax.swing.ButtonGroup tasa_cambio_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bcv_radio = new javax.swing.JRadioButton();
        monitor_dolar_radio = new javax.swing.JRadioButton();
        dolar_paralelo_radio = new javax.swing.JRadioButton();
        personalizado_radio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        monto_personalidado = new javax.swing.JTextField();
        monto_personalidado_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        money_bs = new javax.swing.JLabel();
        money_dolar = new javax.swing.JLabel();
        input = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tasa_cambio_group.add(bcv_radio);
        bcv_radio.setText("BCV");
        bcv_radio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        bcv_radio.setName("tasa_cambio"); // NOI18N
        bcv_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcv_radioActionPerformed(evt);
            }
        });
        jPanel1.add(bcv_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 100, -1, -1));

        tasa_cambio_group.add(monitor_dolar_radio);
        monitor_dolar_radio.setText("Monitor Dolar");
        monitor_dolar_radio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        monitor_dolar_radio.setName("tasa_cambio"); // NOI18N
        jPanel1.add(monitor_dolar_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        tasa_cambio_group.add(dolar_paralelo_radio);
        dolar_paralelo_radio.setText("Dolar Paralelo");
        dolar_paralelo_radio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        dolar_paralelo_radio.setName("tasa_cambio"); // NOI18N
        jPanel1.add(dolar_paralelo_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 100, -1, -1));

        tasa_cambio_group.add(personalizado_radio);
        personalizado_radio.setText("Personalizado");
        personalizado_radio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        personalizado_radio.setName("tasa_cambio"); // NOI18N
        jPanel1.add(personalizado_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Punto de Venta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 780, -1));

        jLabel2.setText("Selección Tasa de cambio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 72, -1, -1));

        monto_personalidado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(monto_personalidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 100, 161, 25));

        monto_personalidado_label.setText("Valor del Dolar");
        jPanel1.add(monto_personalidado_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 72, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Tasa actual");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 73, -1, -1));

        money_bs.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        money_bs.setText("0.00 Bs");
        jPanel1.add(money_bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 123, -1, -1));

        money_dolar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        money_dolar.setText("0.00 $");
        jPanel1.add(money_dolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 100, -1, -1));

        input.setBackground(new java.awt.Color(255, 255, 255));
        input.setFont(new java.awt.Font("Roboto", 0, 34)); // NOI18N
        input.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        input.setText("  $ 0.00");
        input.setAlignmentX(1.0F);
        input.setAlignmentY(1.0F);
        input.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        input.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 163, 298, 54));
        input.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel1);

        jMenu1.setText("Archivo");

        jMenuItem3.setText("Calculadora");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Licencia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenu3.setText("WebSite");

        jMenuItem4.setText("Projecto");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu2.add(jMenu3);

        jMenuItem6.setText("Acerca de Nosotros");
        jMenu2.add(jMenuItem6);

        jMenuItem5.setText("Donaciones");
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator4);

        jMenuItem7.setText("Ayuda");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1020, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void bcv_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcv_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcv_radioActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bcv_radio;
    private javax.swing.JRadioButton dolar_paralelo_radio;
    private javax.swing.JLabel input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel money_bs;
    private javax.swing.JLabel money_dolar;
    private javax.swing.JRadioButton monitor_dolar_radio;
    private javax.swing.JTextField monto_personalidado;
    private javax.swing.JLabel monto_personalidado_label;
    private javax.swing.JRadioButton personalizado_radio;
    // End of variables declaration//GEN-END:variables
}
